version: "3.9"

services:
  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      network_configuration:
        ipv4_address: ${DATABASE_IP}
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]

  backend:
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 5000:5000
    networks:
      network_configuration:
        ipv4_address: ${BACKEND_IP}

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      network_configuration:
        ipv4_address: ${FRONTEND_IP}

networks:
  network_configuration:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
