version: "3.9"

services:
  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_root_password
      DB_PASSWORD: /run/secrets/db_password
    ports:
      - 5432:5432
    secrets:
      - db_root_password
      - db_password

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
